WITH TOP_ARTISTS AS (
SELECT TOP(5) ARTIST_NAME, SUM(STREAMS) AS TOTAL_STREAMS
FROM SPOTIFY_STREAMS
GROUP BY ARTIST_NAME
ORDER BY SUM(STREAMS) DESC),

BOTTOM_ARTISTS AS (
SELECT TOP(5) ARTIST_NAME, SUM(STREAMS) AS TOTAL_STREAMS
FROM SPOTIFY_STREAMS
GROUP BY ARTIST_NAME
ORDER BY SUM(STREAMS))

SELECT * FROM TOP_ARTISTS
UNION ALL
SELECT * FROM BOTTOM_ARTISTS;